name: Test 2
on:
  pull_request:
    paths: ['go/**/*.go']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v5
        with:
          go-verson: '1.22'
      - run: go test go/excellent/*.go